import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import {
  SiFrontendmentor,
  SiAdobeindesign,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiNestjs,
  SiMongodb,
  SiFirebase,
  SiTypescript,
  SiCodewars,
} from "react-icons/si";
import { FaReact } from "react-icons/fa";
import { TbBrandNextjs } from "react-icons/tb";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { CgFigma } from "react-icons/cg";
import { useState } from "react";
import deved from "../public/mypicture.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web11 from "../public/web11.png";
import web22 from "../public/web22.png";
import web33 from "../public/web33.png";
import web44 from "../public/web44.png";
import web55 from "../public/web55.png";
import web66 from "../public/web66.png";

const FirstName = "Viktor Alieksieiev";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>{FirstName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="flex justify-between py-10 mb-12 dark:text-white">
            <h1 className="text-xl lg:text-3xl md:text-2xl lg: font-burtons hover:scale-125">
              @lexaNem0
            </h1>
            <ul className="flex items-center ">
              <li className="transition duration-300 ease-in-out delay-300 hover:rotate-180">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="text-2xl cursor-pointer "
                />
              </li>
              <li className="transition duration-500 ease-in-out delay-300 hover:scale-125">
                <a
                  className="px-4 py-2 ml-8 text-white border-none rounded-md bg-gradient-to-r from-cyan-500 to-teal-500 "
                  href="https://docs.google.com/document/d/1378qwHlOK7TdVfQGt3xQ1ufRf6qmLFnS/edit?usp=sharing&ouid=116848366544717899951&rtpof=true&sd=true"
                  target="blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center">
            <h2 className="py-2 text-5xl font-bold text-teal-600 dark:text-teal-400 md:text-7xl">
              Viktor Alieksieiev
            </h2>
            <h3 className="py-2 text-2xl dark:text-white md:text-4xl">
              Front-end Developer.
            </h3>
            <p className="max-w-xl py-5 mx-auto leading-8 text-gray-800 text-md dark:text-gray-200 md:text-xl">
              Hey there! I am a friendly and passionate front-end developer who
              loves building websites that not only look great but also meet
              your specific goals. I have a knack for collaborating with clients
              like you to understand your requirements, create strategic plans,
              and design websites that are user-friendly and high-performing.
            </p>
            <div className="flex justify-center gap-8 py-3 text-5xl text-gray-600 dark:text-gray-400 sm:gap-16">
              <a
                className="transition duration-300 ease-in-out delay-300 hover:scale-125"
                href="https://github.com/AlexaNem0"
                target="blank"
              >
                <AiFillGithub />
              </a>
              <a
                className="transition duration-300 ease-in-out delay-300 hover:animate-bounce"
                href="https://www.linkedin.com/in/victor-alekseev-936692129/"
                target="blank"
              >
                <AiFillLinkedin />
              </a>
              <a
                className="transition duration-300 ease-in-out delay-300 hover:rotate-180"
                href="https://www.frontendmentor.io/profile/AlexaNem0"
                target="blank"
              >
                <SiFrontendmentor />
              </a>
              <a
                className="transition duration-300 ease-in-out delay-300 hover:rotate-180"
                href="https://www.codewars.com/users/AlexaNem0"
                target="blank"
              >
                <SiCodewars />
              </a>
            </div>
          </div>
          <div className="relative mx-auto my-10 overflow-hidden rounded-full bg-gradient-to-b from-teal-400 w-80 h-80 md:h-96 md:w-96 hover:scale-105">
            <Image
              src={deved}
              layout="fill"
              objectFit="cover"
              alt="Description of the image"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Services I offer</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
              Throughout my freelance career as a designer and developer, I have
              gained experience working remotely for agencies, consulting with
              startups, and collaborating with talented individuals to create
              digital products for both business and consumer purposes.
            </p>
          </div>
          <div className="gap-10 lg:flex">
            <div className="flex-1 p-10 my-10 text-center transition duration-300 ease-in-out delay-300 shadow-lg rounded-xl dark:bg-white hover:scale-110">
              <Image
                src={design}
                width={100}
                height={100}
                alt="Description of the image"
              />
              <h3 className="pt-8 pb-2 text-lg font-bold ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-gray-800 ">
                <span className="inline-flex items-center text-xl">
                  <SiAdobephotoshop className="mr-1 text-3xl text-orange-300" />{" "}
                  PhotoShop
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl">
                  <SiAdobeillustrator className="mr-1 text-3xl text-orange-300" />{" "}
                  Illustrator
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl">
                  <SiAdobeindesign className="mr-1 text-3xl text-orange-300" />{" "}
                  Indesign
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl ">
                  <CgFigma className="mr-1 text-3xl text-orange-300" /> Figma
                </span>
              </p>
            </div>
            <div className="flex-1 p-10 my-10 text-center transition duration-300 ease-in-out delay-300 shadow-lg rounded-xl dark:bg-white hover:scale-110">
              <Image
                src={code}
                width={100}
                height={100}
                alt="Description of the image"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make
                it a reality.
              </p>
              <h4 className="py-4 text-teal-600">Frond End Tools I Use</h4>

              <p className="py-1 text-gray-800">
                <p className="py-1 text-gray-800">
                  <span className="inline-flex items-center text-xl ">
                    <SiJavascript className="mr-2 text-3xl text-orange-300" />
                    JavaScript
                  </span>
                </p>
                <p className="py-1 text-gray-800">
                  <span className="inline-flex items-center text-xl ">
                    <SiTypescript className="mr-2 text-3xl text-orange-300" />
                    TypeScript
                  </span>
                </p>
                <p className="py-1 text-gray-800">
                  <span className="inline-flex items-center text-xl ">
                    <FaReact className="mr-1 text-3xl text-orange-300" />
                    ReactJS
                  </span>
                </p>
                <span className="inline-flex items-center text-xl ">
                  <SiHtml5 className="mr-1 text-3xl text-orange-300" /> HTML
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl ">
                  <SiCss3 className="mr-1 text-3xl text-orange-300" /> CSS
                </span>
              </p>
            </div>
            <div className="flex-1 p-10 my-10 text-center transition duration-300 ease-in-out delay-300 shadow-lg rounded-xl dark:bg-white hover:scale-110">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="Description of the image"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Back End Support
              </h3>
              <p className="py-2">
                Do you require Back End support for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Back End Tools I Use</h4>
              <p className="py-1 text-gray-800 ">
                <span className="inline-flex items-center text-xl ">
                  <SiFirebase className="mr-1 text-3xl text-orange-300" />
                  FireBase
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl ">
                  <SiMongodb className="mr-1 text-3xl text-orange-300" />
                  MongoDB
                </span>
              </p>

              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl ">
                  <TbBrandNextjs className="mr-1 text-3xl text-orange-300" />
                  NextJS
                </span>
              </p>
              <p className="py-1 text-gray-800">
                <span className="inline-flex items-center text-xl ">
                  <SiNestjs className="mr-1 text-3xl text-orange-300" />
                  NestJS
                </span>
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Portofolio</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-gray-200">
              Welcome to my front-end developer portfolio! I am thrilled to
              showcase my skills and expertise in creating visually stunning and
              highly functional websites. With a passion for design and a knack
              for coding, I specialize in delivering seamless user experiences
              that engage and captivate audiences.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://myomnifoodpr.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-fill rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web11}
                  alt="Omnifood"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page HTML CSS JavaScript
                  </p>
                </div>
              </a>
            </div>

            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://frontmanagelp.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-fill rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web22}
                  alt="Manage"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page HTML Tailwind JavaScript
                  </p>
                </div>
              </a>
            </div>
            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://ultraeats.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-cover rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web33}
                  alt="Ultraeats"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page ReactJS Tailwind
                  </p>
                </div>
              </a>
            </div>
            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://alexrockets.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-cover rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web44}
                  alt="Rockets"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page HTML Tailwind JavaScript
                  </p>
                </div>
              </a>
            </div>
            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://fylofem1.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-cover rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web55}
                  alt="Description of the image"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page ReactJS Tailwind
                  </p>
                </div>
              </a>
            </div>
            <div className="relative flex-1 basis-1/3 hover:scale-105">
              <a
                href="https://notrealtradeapp.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="object-cover rounded-lg"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web66}
                  alt="Not Real Trade App"
                />
                <div className="absolute inset-0 flex items-center justify-center text-white transition-opacity duration-300 bg-black rounded-lg opacity-0 bg-opacity-60 hover:opacity-100 ">
                  <p className="text-lg text-orange-100 md:font-semibold md:text-lg lg:text-2xl">
                    Landing page ReactJS Tailwind
                  </p>
                </div>
              </a>
            </div>
          </div>
        </section>
      </main>
      <section>
        <div className="flex items-center justify-center p-12 dark:text-teal-400 dark:bg-gray-900 ">
          <div className="mx-auto w-full   max-w-[550px]">
            <h2 className="mb-10 text-xl">Let&apos;s get in touch!</h2>
            <form action="https://formbold.com/s/9BvZw" method="POST">
              <div className="mb-5">
                <label
                  htmlFor="name"
                  className="mb-3 block text-base font-medium text-[#07074D] dark:text-teal-400"
                >
                  Full Name
                </label>
                <input
                  type="text"
                  name="name"
                  id="name"
                  placeholder="Full Name"
                  required
                  className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md "
                />
              </div>
              <div className="mb-5">
                <label
                  htmlFor="email"
                  className="mb-3 block text-base font-medium text-[#07074D] dark:text-teal-400"
                >
                  Email Address
                </label>
                <input
                  type="email"
                  name="email"
                  id="email"
                  placeholder="example@domain.com"
                  required
                  className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
              </div>
              <div className="mb-5">
                <label
                  htmlFor="subject"
                  className="mb-3 block text-base font-medium text-[#07074D]dark:text-teal-400"
                >
                  Subject
                </label>
                <input
                  type="text"
                  name="subject"
                  id="subject"
                  required
                  placeholder="Enter your subject"
                  className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
              </div>
              <div className="mb-5">
                <label
                  htmlFor="message"
                  className="mb-3 block text-base font-medium text-[#07074D]dark:text-teal-400"
                >
                  Message
                </label>
                <textarea
                  rows="4"
                  name="message"
                  id="message"
                  required
                  placeholder="Type your message"
                  className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                ></textarea>
              </div>
              <div>
                <button className="px-8 py-3 text-base font-semibold text-white transition duration-500 ease-in-out delay-300 rounded-md outline-none hover:shadow-form bg-gradient-to-r from-cyan-500 to-teal-500 hover:scale-125">
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
